name: figma_native_splash
description: Generate native splash screens and app icons for Android, iOS, and HarmonyOS from Figma designs, with snapshots and offline generation.
version: 0.1.1
repository: https://github.com/rx123rx/figma_native_splash
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  http: ^1.4.0
  image: ^4.5.4
  path: ^1.9.1
  xml: ^6.5.0
  yaml: ^3.1.3
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
executables:
  figma_native_splash: figma_native_splash
topics:
  - flutter
  - figma
  - launch-icon
  - splash-screen
  - code-generation
