import 'package:image/image.dart' as img;
import 'package:xml/xml.dart';
import 'config.dart';
import 'snapshot.dart';
import 'output.dart';
import 'artwork.dart';

void generateAndroid(
  OutputPlan plan,
  SplashConfig config,
  DesignSnapshot snapshot,
) {
  final res = config.paths['android_res']!, prefix = config.prefix;
  final phone = snapshot.frames['phone']!,
      tablet = snapshot.frames['tablet'] ?? phone;
  for (final role in ['background', 'foreground', 'branding']) {
    plan.bytes(
      '$res/drawable-nodpi/${prefix}_$role.png',
      snapshot.assets[phone.layers[role]!.asset]!,
    );
    plan.bytes(
      '$res/drawable-w600dp-nodpi/${prefix}_$role.png',
      snapshot.assets[tablet.layers[role]!.asset]!,
    );
  }
  plan.bytes(
    '$res/drawable-xxxhdpi/${prefix}_system_icon.png',
    img.encodePng(
      systemIcon(snapshot.image(phone.layers['foreground']!.asset)),
    ),
  );
  plan.bytes(
    '$res/drawable-xxxhdpi-v31/${prefix}_system_brand.png',
    img.encodePng(systemBrand(snapshot.image(phone.layers['branding']!.asset))),
  );
  final windows = {
    '': [320.0, 320.0],
    '-h400dp': [375.0, 550.0],
    '-h600dp': [375.0, 812.0],
    '-w600dp': [600.0, 320.0],
    '-w600dp-h400dp': [834.0, 500.0],
    '-w600dp-h600dp': [834.0, 1194.0],
    '-w840dp-h600dp': [1194.0, 834.0],
  };
  for (final entry in windows.entries) {
    final width = entry.value[0], height = entry.value[1];
    final layout = fitLayout(snapshot, width, height);
    final values = {
      'foreground_width': layout.foreground.width,
      'foreground_height': layout.foreground.height,
      'foreground_shift':
          (layout.foreground.x + layout.foreground.width / 2 - width / 2) * 2,
      'foreground_inset':
          height - 2 * (layout.foreground.y + layout.foreground.height / 2),
      'branding_width': layout.branding.width,
      'branding_height': layout.branding.height,
      'branding_shift':
          (layout.branding.x + layout.branding.width / 2 - width / 2) * 2,
      'branding_bottom': height - layout.branding.y - layout.branding.height,
    };
    plan.text(
      '$res/values${entry.key}/$prefix.xml',
      '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${values.entries.map((e) => '    <dimen name="${prefix}_${e.key}">${e.value.toStringAsFixed(3)}dp</dimen>').join('\n')}\n</resources>\n',
    );
  }
  final fg = phone.layers['foreground']!.rect;
  final inset = (1 - 2 * (fg.y + fg.height / 2) / phone.height) * 100;
  String drawable(bool fractional) =>
      '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by figma_native_splash. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:paddingMode="stack">
  <item android:drawable="@color/${prefix}_surface"/>
  <item><bitmap android:src="@drawable/${prefix}_background" android:gravity="fill" android:filter="true"/></item>
  <item><inset android:insetLeft="@dimen/${prefix}_foreground_shift" android:insetBottom="${fractional ? '${inset.toStringAsFixed(3)}%' : '@dimen/${prefix}_foreground_inset'}"><layer-list>
    <item android:width="@dimen/${prefix}_foreground_width" android:height="@dimen/${prefix}_foreground_height" android:gravity="center"><bitmap android:src="@drawable/${prefix}_foreground" android:gravity="fill" android:filter="true"/></item>
  </layer-list></inset></item>
  <item><inset android:insetLeft="@dimen/${prefix}_branding_shift"><layer-list>
    <item android:bottom="@dimen/${prefix}_branding_bottom" android:width="@dimen/${prefix}_branding_width" android:height="@dimen/${prefix}_branding_height" android:gravity="bottom|center_horizontal"><bitmap android:src="@drawable/${prefix}_branding" android:gravity="fill" android:filter="true"/></item>
  </layer-list></inset></item>
</layer-list>
''';
  plan.text('$res/drawable/${prefix}_launch.xml', drawable(false));
  plan.text('$res/drawable-v26/${prefix}_launch.xml', drawable(true));
  plan.text(
    '$res/values/${prefix}_colors.xml',
    '<?xml version="1.0" encoding="utf-8"?>\n<resources><color name="${prefix}_surface">${config.color}</color></resources>\n',
  );
  final baseFile = '$res/values/styles.xml';
  final baseDoc = XmlDocument.parse(plan.read(baseFile));
  final baseTheme = baseDoc
      .findAllElements('style')
      .where((e) => e.getAttribute('name') == 'LaunchTheme')
      .toList();
  if (baseTheme.length != 1) {
    throw SplashException('Android 必须存在唯一 LaunchTheme：$baseFile');
  }
  for (final folder in [
    'values',
    'values-night',
    'values-v31',
    'values-night-v31',
  ]) {
    final file = '$res/$folder/styles.xml';
    XmlDocument document;
    try {
      document = XmlDocument.parse(plan.read(file));
    } on SplashException {
      document = XmlDocument.parse('<resources/>');
    }
    final candidates = document
        .findAllElements('style')
        .where((e) => e.getAttribute('name') == 'LaunchTheme')
        .toList();
    if (candidates.length > 1) {
      throw SplashException('Android 存在多个 LaunchTheme：$file');
    }
    final theme = candidates.isEmpty
        ? baseTheme.single.copy()
        : candidates.single;
    if (candidates.isEmpty) document.rootElement.children.add(theme);
    final values = {
      'android:windowBackground': '@drawable/${prefix}_launch',
      'android:forceDarkAllowed': 'false',
      'android:windowDrawsSystemBarBackgrounds': 'true',
      'android:statusBarColor': '@color/${prefix}_surface',
      'android:navigationBarColor': '@color/${prefix}_surface',
      'android:windowLightStatusBar': '${color(config.color).luminance > 128}',
      'android:windowLightNavigationBar':
          '${color(config.color).luminance > 128}',
      if (folder.endsWith('-v31')) ...{
        'android:windowSplashScreenBackground': '@color/${prefix}_surface',
        'android:windowSplashScreenAnimatedIcon':
            '@drawable/${prefix}_system_icon',
        'android:windowSplashScreenBrandingImage':
            '@drawable/${prefix}_system_brand',
      },
    };
    for (final entry in values.entries) {
      final existing = theme
          .findElements('item')
          .where((e) => e.getAttribute('name') == entry.key)
          .toList();
      final item = existing.isEmpty
          ? XmlElement(XmlName('item'), [
              XmlAttribute(XmlName('name'), entry.key),
            ])
          : existing.first;
      for (final duplicate in existing.skip(1)) {
        duplicate.parent?.children.remove(duplicate);
      }
      item.children
        ..clear()
        ..add(XmlText(entry.value));
      if (existing.isEmpty) theme.children.add(item);
    }
    plan.text(
      file,
      '${document.toXmlString(pretty: true, indent: '    ')}\n',
      own: false,
    );
  }
}
