import 'dart:convert';
import 'dart:io';
import 'package:image/image.dart' as img;
import 'package:xml/xml.dart';
import 'config.dart';
import 'icon_config.dart';
import 'icon_snapshot.dart';
import 'output.dart';
import 'artwork.dart';
import 'xcode_project.dart';
import 'json5_edit.dart';

img.Image opaqueIcon(img.Image source, String? background) {
  if (background == null && source.any((pixel) => pixel.aNormalized < 1)) {
    throw SplashException(
      '图标有透明区域，请配置 icon.background_color 或在 Figma 中提供不透明背景',
    );
  }
  final output = img.Image(
    width: source.width,
    height: source.height,
    numChannels: 3,
  );
  if (background != null) img.fill(output, color: color(background));
  img.compositeImage(output, source);
  return output;
}

/// Adaptive artwork is assembled from its designated layers so optional
/// monochrome/reference layers cannot leak into the full-color app icon.
img.Image fullColorIcon(IconConfig config, IconSnapshot snapshot) {
  if (!config.roles.contains('foreground')) {
    return opaqueIcon(snapshot.image('icon'), config.background);
  }
  final background = opaqueIcon(
    snapshot.image('background'),
    config.background,
  );
  final foreground = snapshot.image('foreground');
  img.compositeImage(
    background,
    img.copyResize(
      foreground,
      width: background.width,
      height: background.height,
    ),
  );
  return background;
}

List<int> sizedIcon(img.Image image, int pixels) => img.encodePng(
  img.copyResize(
    image,
    width: pixels,
    height: pixels,
    interpolation: img.Interpolation.average,
  ),
);
img.Image monochromeIcon(img.Image image) {
  var transparent = false, visible = false;
  final output = img.Image(
    width: image.width,
    height: image.height,
    numChannels: 4,
  );
  for (final pixel in image) {
    if (pixel.aNormalized == 0) transparent = true;
    if (pixel.aNormalized > 0) visible = true;
    output.setPixelRgba(
      pixel.x,
      pixel.y,
      255,
      255,
      255,
      (pixel.aNormalized * 255).round(),
    );
  }
  if (!transparent || !visible) {
    throw SplashException('icon/monochrome 必须同时有透明背景和非透明轮廓；不支持用白底黑图代替透明蒙版');
  }
  return output;
}

OutputPlan generateIcons(
  Directory root,
  IconConfig config,
  IconSnapshot snapshot, {
  List<String>? platforms,
}) {
  snapshot.validate(config);
  final selected = platforms ?? config.platforms;
  if (selected.any((v) => !config.platforms.contains(v))) {
    throw SplashException('所选平台未在 icon.platforms 中启用');
  }
  final image = fullColorIcon(config, snapshot);
  final plan = OutputPlan(root);
  for (final platform in selected) {
    final output = OutputPlan(root);
    switch (platform) {
      case 'android':
        _android(output, config, snapshot, image);
      case 'ios':
        _ios(output, config, image);
      case 'ohos':
        _ohos(output, config, image);
      default:
        throw SplashException('未知图标平台：$platform');
    }
    output.track('icon_$platform', config.prefix);
    plan.merge(output);
  }
  return plan;
}

void _android(
  OutputPlan plan,
  IconConfig c,
  IconSnapshot snapshot,
  img.Image icon,
) {
  final res = c.paths['android_res']!, name = c.prefix;
  for (final entry in {
    'mdpi': 48,
    'hdpi': 72,
    'xhdpi': 96,
    'xxhdpi': 144,
    'xxxhdpi': 192,
  }.entries) {
    plan.bytes(
      '$res/mipmap-${entry.key}/$name.png',
      sizedIcon(icon, entry.value),
    );
  }
  if (c.adaptive) {
    plan.bytes(
      '$res/drawable-xxxhdpi/${name}_background.png',
      sizedIcon(opaqueIcon(snapshot.image('background'), c.background), 432),
    );
    plan.bytes(
      '$res/drawable-xxxhdpi/${name}_foreground.png',
      sizedIcon(snapshot.image('foreground'), 432),
    );
    String xml(bool mono) =>
        '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by figma_native_splash icon. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/${name}_background"/>
  <foreground android:drawable="@drawable/${name}_foreground"/>
  ${mono ? '<monochrome android:drawable="@drawable/${name}_monochrome"/>' : ''}
</adaptive-icon>
''';
    plan.text('$res/mipmap-anydpi-v26/$name.xml', xml(false));
    if (c.monochrome) {
      plan.bytes(
        '$res/drawable-xxxhdpi/${name}_monochrome.png',
        sizedIcon(monochromeIcon(snapshot.image('monochrome')), 432),
      );
      plan.text('$res/mipmap-anydpi-v33/$name.xml', xml(true));
    }
  }
  final document = XmlDocument.parse(plan.read(c.androidManifest));
  final apps = document.rootElement.findElements('application').toList();
  if (apps.length != 1) {
    throw SplashException('AndroidManifest.xml 必须包含唯一 application');
  }
  final app = apps.single;
  app.setAttribute('android:icon', '@mipmap/$name');
  app.setAttribute('android:roundIcon', '@mipmap/$name');
  // Launcher aliases/activities may override the application icon.
  for (final activity in app.childElements.where(
    (e) => ['activity', 'activity-alias'].contains(e.name.local),
  )) {
    final launcher = activity
        .findElements('intent-filter')
        .any(
          (filter) =>
              filter
                  .findElements('action')
                  .any(
                    (e) =>
                        e.getAttribute('android:name') ==
                        'android.intent.action.MAIN',
                  ) &&
              filter
                  .findElements('category')
                  .any(
                    (e) =>
                        e.getAttribute('android:name') ==
                        'android.intent.category.LAUNCHER',
                  ),
        );
    if (launcher) {
      for (final attr in ['android:icon', 'android:roundIcon']) {
        if (activity.getAttribute(attr) != null) {
          activity.setAttribute(attr, '@mipmap/$name');
        }
      }
    }
  }
  plan.text(
    c.androidManifest,
    '${document.toXmlString(pretty: true)}\n',
    own: false,
  );
}

void _ios(OutputPlan plan, IconConfig c, img.Image icon) {
  final runner = c.paths['ios_runner']!,
      folder =
          '${c.paths['ios_runner']}/Assets.xcassets/${c.prefix}.appiconset';
  final entries = <Map<String, String>>[];
  final files = <int>{};
  void add(String idiom, num size, int scale) {
    final pixels = (size * scale).round();
    files.add(pixels);
    entries.add({
      'idiom': idiom,
      'size': '${size}x$size',
      'scale': '${scale}x',
      'filename': 'icon-$pixels.png',
    });
  }

  for (final size in [20, 29, 40, 60]) {
    for (final scale in [2, 3]) {
      add('iphone', size, scale);
    }
  }
  for (final size in [20, 29, 40, 76]) {
    for (final scale in [1, 2]) {
      add('ipad', size, scale);
    }
  }
  add('ipad', 83.5, 2);
  add('ios-marketing', 1024, 1);
  for (final pixels in files) {
    plan.bytes('$folder/icon-$pixels.png', sizedIcon(icon, pixels));
  }
  plan.text(
    '$folder/Contents.json',
    '${const JsonEncoder.withIndent('  ').convert({
      'images': entries,
      'info': {'version': 1, 'author': 'figma_native_splash'},
    })}\n',
  );
  integrateIosAppIcon(plan, runner, c.prefix);
}

void _ohos(OutputPlan plan, IconConfig c, img.Image icon) {
  final main = c.paths['ohos_main']!, scope = c.ohosAppScope, name = c.prefix;
  plan.bytes('$main/resources/base/media/$name.png', sizedIcon(icon, 1024));
  plan.bytes(
    '$scope/resources/base/media/${name}_app.png',
    sizedIcon(icon, 1024),
  );
  final appPath = '$scope/app.json5', modulePath = '$main/module.json5';
  final app = Json5Object.root(plan.read(appPath)).object('app');
  plan.text(appPath, app.setString('icon', '\$media:${name}_app'), own: false);
  final module = Json5Object.root(plan.read(modulePath)).object('module');
  final abilities = module
      .objects('abilities')
      .where((a) => a.string('name') == c.ability)
      .toList();
  if (abilities.length != 1) {
    throw SplashException('找不到唯一鸿蒙 Ability：${c.ability}');
  }
  plan.text(
    modulePath,
    abilities.single.setString('icon', '\$media:$name'),
    own: false,
  );
}

Map<String, List<int>> iconPreviews(IconConfig c, IconSnapshot snapshot) {
  snapshot.validate(c);
  final full = fullColorIcon(c, snapshot);
  final assets = <String, List<int>>{'icon.png': sizedIcon(full, 512)};
  if (c.platforms.contains('android') && c.adaptive) {
    final background = img.copyResize(
      opaqueIcon(snapshot.image('background'), c.background),
      width: 432,
      height: 432,
    );
    img.compositeImage(
      background,
      img.copyResize(snapshot.image('foreground'), width: 432, height: 432),
    );
    // Adaptive launcher masks act on the central 72dp of a 108dp layer.
    final cropped = img.copyCrop(
      background,
      x: 72,
      y: 72,
      width: 288,
      height: 288,
    );
    for (final shape in ['circle', 'rounded_square']) {
      final preview = img.Image(width: 288, height: 288, numChannels: 4);
      for (final px in cropped) {
        final x = px.x - 143.5, y = px.y - 143.5;
        final inside = shape == 'circle'
            ? x * x + y * y <= 144 * 144
            : ((x.abs() - 96).clamp(0, 144) * (x.abs() - 96).clamp(0, 144) +
                      (y.abs() - 96).clamp(0, 144) *
                          (y.abs() - 96).clamp(0, 144) <=
                  48 * 48);
        if (inside) preview.setPixel(px.x, px.y, px);
      }
      assets['android_$shape.png'] = img.encodePng(preview);
    }
    if (c.monochrome) {
      assets['android_monochrome.png'] = sizedIcon(
        monochromeIcon(snapshot.image('monochrome')),
        432,
      );
    }
  }
  return assets;
}
