const iosTemplate = r'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by figma_native_splash. -->
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="23501" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <device id="retina6_12" orientation="portrait" appearance="light"/>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="23501"/>
        <capability name="Safe area layout guides" minToolsVersion="9.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <scenes>
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <rect key="frame" x="0.0" y="0.0" width="393" height="852"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" image="LaunchBackground" translatesAutoresizingMaskIntoConstraints="NO" id="splash-background" userLabel="Gradient background"/>
                            <imageView userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="1" verticalHuggingPriority="1" horizontalCompressionResistancePriority="1" verticalCompressionResistancePriority="1" image="LaunchHeadline" translatesAutoresizingMaskIntoConstraints="NO" id="splash-headline" userLabel="Headline and flourish">
                                <constraints>
                                    <constraint firstAttribute="width" secondItem="splash-headline" secondAttribute="height" multiplier="227.172:199" id="headline-aspect"/>
                                    <constraint firstAttribute="width" relation="lessThanOrEqual" constant="350" id="headline-max-width"/>
                                </constraints>
                            </imageView>
                            <imageView userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="1" verticalHuggingPriority="1" horizontalCompressionResistancePriority="1" verticalCompressionResistancePriority="1" image="LaunchBrand" translatesAutoresizingMaskIntoConstraints="NO" id="splash-brand" userLabel="Brand and tagline">
                                <constraints>
                                    <constraint firstAttribute="width" secondItem="splash-brand" secondAttribute="height" multiplier="148:50" id="brand-aspect"/>
                                    <constraint firstAttribute="width" relation="lessThanOrEqual" constant="272" id="brand-max-width"/>
                                </constraints>
                            </imageView>
                        </subviews>
                        <viewLayoutGuide key="safeArea" id="splash-safe-area"/>
                        <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                        <constraints>
                            <constraint firstItem="splash-background" firstAttribute="leading" secondItem="Ze5-6b-2t3" secondAttribute="leading" id="background-leading"/>
                            <constraint firstItem="splash-background" firstAttribute="trailing" secondItem="Ze5-6b-2t3" secondAttribute="trailing" id="background-trailing"/>
                            <constraint firstItem="splash-background" firstAttribute="top" secondItem="Ze5-6b-2t3" secondAttribute="top" id="background-top"/>
                            <constraint firstItem="splash-background" firstAttribute="bottom" secondItem="Ze5-6b-2t3" secondAttribute="bottom" id="background-bottom"/>
                            <!-- Width interpolates the two portrait references; height caps protect short windows. -->
                            <constraint firstItem="splash-headline" firstAttribute="width" secondItem="Ze5-6b-2t3" secondAttribute="width" multiplier="0.26634" constant="127.29" priority="750" id="headline-preferred-width"/>
                            <constraint firstItem="splash-headline" firstAttribute="width" relation="lessThanOrEqual" secondItem="splash-safe-area" secondAttribute="width" constant="-48" id="headline-window-width"/>
                            <constraint firstItem="splash-headline" firstAttribute="height" relation="lessThanOrEqual" secondItem="splash-safe-area" secondAttribute="height" multiplier="0.38" id="headline-window-height"/>
                            <constraint firstItem="splash-headline" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" constant="14" id="headline-optical-center"/>
                            <constraint firstItem="splash-headline" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" multiplier="0.698" constant="37.5" priority="750" id="headline-vertical-position"/>
                            <constraint firstItem="splash-headline" firstAttribute="top" relation="greaterThanOrEqual" secondItem="splash-safe-area" secondAttribute="top" constant="24" id="headline-safe-top"/>
                            <constraint firstItem="splash-brand" firstAttribute="top" relation="greaterThanOrEqual" secondItem="splash-headline" secondAttribute="bottom" constant="32" id="headline-brand-gap"/>
                            <constraint firstItem="splash-brand" firstAttribute="width" secondItem="Ze5-6b-2t3" secondAttribute="width" multiplier="0.27252" constant="45" priority="750" id="brand-preferred-width"/>
                            <constraint firstItem="splash-brand" firstAttribute="width" relation="lessThanOrEqual" secondItem="splash-safe-area" secondAttribute="width" constant="-48" id="brand-window-width"/>
                            <constraint firstItem="splash-brand" firstAttribute="height" relation="lessThanOrEqual" secondItem="splash-safe-area" secondAttribute="height" multiplier="0.16" id="brand-window-height"/>
                            <constraint firstItem="splash-brand" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="brand-center"/>
                            <constraint firstItem="splash-brand" firstAttribute="bottom" secondItem="Ze5-6b-2t3" secondAttribute="bottom" multiplier="0.943" constant="-15" priority="750" id="brand-preferred-bottom"/>
                            <constraint firstItem="splash-brand" firstAttribute="bottom" relation="lessThanOrEqual" secondItem="splash-safe-area" secondAttribute="bottom" constant="-16" id="brand-safe-bottom"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
        </scene>
    </scenes>
    <resources>
        <image name="LaunchBackground" width="375" height="812"/>
        <image name="LaunchHeadline" width="227.172" height="199"/>
        <image name="LaunchBrand" width="148" height="50"/>
    </resources>
</document>
''';
